[package]
name = "omt"
version = "0.1.0"
edition = "2024"

[dependencies]
omt-sys = { path = "../omt-sys" }
thiserror = "2.0"
bitflags = "2.6"
rgb = "0.8.52"
yuv = "0.8.11"

[dev-dependencies]
image = "0.25"
clap = { version = "4.5", features = ["derive"] }
viuer = "0.11.0"
